# Interior Point Quadratic Programming

Solve quadratic problem
$$ \min  q(x) = \frac{1}{2} x^T G x + x^T c $$
$$ \textrm{s.t.} \quad Ax \geq b.$$
Using the interior point method described by Nocedal.

## Example of a 2-dimensional problem

From p. 475 (Nocedal)

$$ \min f(x) = (x_1 - 1)^2 + (x_2 - 2.5)^2 $$
subject to
$$\begin{align*}
 x_1 - 2x_2 + 2 &\geq 0, \\
-x_1 - 2x_2 + 6 &\geq 0, \\
-x_1 + 2x_2 + 2 &\geq 0, \\
            x_1 &\geq 0, \\
            x_2 &\geq 0. \\
\end{align*}$$

Observe that 
$$\begin{align*}
(x_1-1)^2+(x_2-2.5)^2
&= x_1^2 -2 x_1 + 1 + x_2^2 - 5x_2 + 6.25 \\
&= x_1^2 + x_2^2 -2x_1 -5 x_2 + 7.25\\
&= \frac{1}{2} \vec{x} 
    \begin{pmatrix}
    2 & 0 \\
    0 & 2
    \end{pmatrix} \vec{x} + (-2, -5)^T \vec{x} + 7.25 \\
&= \frac{1}{2} \vec{x}^T G \vec{x} + c^T \vec{x} + 7.25.
\end{align*}$$

and the restrictions are of the form $A\vec{x} \geq b$ with $$ A = \begin{pmatrix}
 1 & -2 \\
-1 & -1 \\
-1 &  2 \\
 1 &  0 \\
 0 &  1
\end{pmatrix} $$
and
$$b = \begin{pmatrix}
-2 \\
-6 \\
-2 \\
 0 \\
 0
\end{pmatrix}
$$

In [1]:
import numpy as np
from optimus import int_point_qp
from scipy.optimize import minimize, Bounds, LinearConstraint

In [2]:
G = np.array([[2,0],[0,2]])
c = np.array([-2,-5])
A = np.array([
    [ 1, -2],
    [-1, -1],
    [-1,  2],
    [ 1,  0],
    [ 0,  1]
])
b = np.array([-2,-6,-2,0,0])

def fun(x):
    return 0.5*np.dot(x,np.dot(G,x)) + np.dot(c, x)

### Example using SciPy

In [3]:
constr = LinearConstraint(A, b, [np.inf]*5)
x0 = np.array([2.,0.])
res = minimize(fun=fun, x0=x0, method='trust-constr', constraints=constr)
res.x # should be (1.4,1.7)

array([1.40001428, 1.69998713])

### Example using `optimus.int_point_qp` method

In [4]:
x, y, lam = int_point_qp(G=G, c=c, A=A, b=b, x_0=x0.copy(), sigma=0.1, maxiters=100)

iter 0:
 - x: [2. 0.]
 - y: [1. 1. 1. 1. 1.]
 - l: [1. 1. 1. 1. 1.]
iter 1:
 - x: [2.0047619  0.14285714]
 - y: [1.01904762 1.15238095 1.18095238 1.1047619  1.04285714]
 - l: [0.89095238 0.75761905 0.72904762 0.8052381  0.86714286]
iter 2:
 - x: [1.99128458 0.27760314]
 - y: [1.00607829 1.30111228 1.37392171 1.18128458 1.08760314]
 - l: [0.82190211 0.59177412 0.54452777 0.67696893 0.7517291 ]
iter 3:
 - x: [1.96505505 0.40480344]
 - y: [0.96844818 1.44314151 1.57355182 1.23605505 1.13380344]
 - l: [0.77832999 0.47408933 0.41672322 0.58459267 0.65190974]
iter 4:
 - x: [1.9311981  0.52426079]
 - y: [0.91437653 1.57624111 1.77342347 1.2750981  1.18036079]
 - l: [0.75129621 0.3878829  0.32663792 0.51342082 0.56622106]
iter 5:
 - x: [1.89364836 0.63552847]
 - y: [0.85112142 1.69935317 1.96789858 1.30315836 1.22601847]
 - l: [0.73514076 0.32286018 0.2617643  0.45580044 0.49312005]
iter 6:
 - x: [1.85508685 0.73829   ]
 - y: [0.78418385 1.81230015 2.15293415 1.32364585 1.269731  ]
 - l: [0.72

In [5]:
x

array([1.40004415, 1.69993593])

In [6]:
np.dot(A,x) >= b

array([ True,  True,  True,  True,  True])